# Generated by Django 2.2.9 on 2022-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=255, verbose_name='nome_livro')),
                ('ano_lancamento', models.CharField(max_length=20, verbose_name='ano_lancamento')),
            ],
            options={
                'db_table': 'livro',
            },
        ),
    ]
